{
  id: 6,
  name: "Pancakes",
  category: "breakfast",
  cuisine: "American",
  emoji: "🥞",
  ingredients: ["Flour", "Milk", "Eggs", "Sugar"],
  instructions: "Mix ingredients and fry on a pan.",
  isFavorite: false,
},
{
  id: 7,
  name: "Fried Rice",
  category: "dinner",
  cuisine: "Nigerian",
  emoji: "🍛",
  ingredients: ["Rice", "Vegetables", "Chicken", "Seasoning"],
  instructions: "Cook rice and stir-fry with vegetables.",
  isFavorite: false,
},
{
  id: 8,
  name: "Ice Cream Sundae",
  category: "dessert",
  cuisine: "American",
  emoji: "🍨",
  ingredients: ["Ice cream", "Chocolate syrup", "Nuts"],
  instructions: "Combine ingredients and serve chilled.",
  isFavorite: false,
},
{
  id: 9,
  name: "Popcorn",
  category: "snack",
  cuisine: "International",
  emoji: "🍿",
  ingredients: ["Corn kernels", "Butter", "Salt"],
  instructions: "Pop kernels and season.",
  isFavorite: false,
},
{
  id: 10,
  name: "Akara",
  category: "breakfast",
  cuisine: "Nigerian",
  emoji: "🧆",
  ingredients: ["Beans", "Pepper", "Onions"],
  instructions: "Blend beans mixture and deep fry.",
  isFavorite: false,
},
{
  id: 11,
  name: "Burger",
  category: "lunch",
  cuisine: "American",
  emoji: "🍔",
  ingredients: ["Bun", "Beef patty", "Lettuce", "Tomato"],
  instructions: "Assemble ingredients and serve.",
  isFavorite: false,
},
{
  id: 12,
  name: "Pizza",
  category: "dinner",
  cuisine: "Italian",
  emoji: "🍕",
  ingredients: ["Dough", "Cheese", "Tomato sauce"],
  instructions: "Bake until golden brown.",
  isFavorite: false,
},
{
  id: 13,
  name: "Fruit Salad",
  category: "snack",
  cuisine: "International",
  emoji: "🍓",
  ingredients: ["Apple", "Banana", "Mango", "Grapes"],
  instructions: "Chop fruits and mix.",
  isFavorite: false,
},
{
  id: 14,
  name: "Cheesecake",
  category: "dessert",
  cuisine: "American",
  emoji: "🍰",
  ingredients: ["Cream cheese", "Sugar", "Biscuits"],
  instructions: "Bake and chill before serving.",
  isFavorite: false,
},
{
  id: 15,
  name: "Egusi Soup",
  category: "dinner",
  cuisine: "Nigerian",
  emoji: "🍲",
  ingredients: ["Egusi", "Vegetables", "Meat", "Palm oil"],
  instructions: "Cook ingredients together until done.",
  isFavorite: false,
}
